name: keepalive
on:
  schedule:
    - cron: "0 0 1 */1 *"   # 每月1号运行一次
  workflow_dispatch:
permissions:
  contents: write
  actions: write
jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
