name: checkin

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  SKLandCheckIn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Prepare module
      run: |
        pip3 install requests
    - name: Run Checkin
      env:
        UID: ${{ secrets.UID }}
        TOKEN: ${{ secrets.TOKEN }}
        DINGTALKTOKEN: ${{ secrets.DINGTALKTOKEN }}
      run: |
        python checkin.py ${UID} ${TOKEN} ${DINGTALKTOKEN}
